{ config, pkgs, lib, ... }:
{

  imports = [
    ./secrets
    ./backups.nix
    ./programs.nix
    ./ppd-hooks.nix
    ./filesystems.nix
    ./hardware-configuration.nix
  ];

  gradient.profiles.gaming.enable = true;
  gradient.profiles.gaming.emulation.romPath = "/data/roms";
  gradient.profiles.desktop.enable = true;
  gradient.profiles.desktop.wayland.autologin.enable = false;
  gradient.profiles.development.enable = true;
  gradient.profiles.catppuccin.enable = true;

  gradient.presets.syncthing.enable = true;

  hardware.gpd-fan.enable = true;
  hardware.fancontrol = {
    enable = true;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon0=devices/pci0000:00/0000:00:02.4/0000:02:00.0/nvme/nvme0 hwmon2=devices/platform/gpd_fan
      DEVNAME=hwmon0=nvme hwmon2=gpdfan
      FCTEMPS=hwmon2/pwm1=hwmon0/temp2_input
      FCFANS= hwmon2/pwm1=hwmon2/fan1_input
      MINTEMP=hwmon2/pwm1=20
      MAXTEMP=hwmon2/pwm1=60
      MINSTART=hwmon2/pwm1=130
      MINSTOP=hwmon2/pwm1=20
    '';
  };
  
  # Android app support with waydroid.
  virtualisation.waydroid.enable = true;

  # Disable automatic login.
  services.displayManager.autoLogin.enable = lib.mkForce false;

  specialisation.deck-ui.configuration = { ... }:
  {
    # Use Jovian's steam deck UI autostart.
    services.displayManager.sddm.enable = lib.mkForce false;
    services.displayManager.autoLogin.enable = lib.mkForce false;
    jovian.steam.autoStart = lib.mkForce true;
  };

  jovian.steam.enable = true;
  jovian.steam.autoStart = false;
  jovian.steam.user = "vera";
  jovian.decky-loader.enable = true;
  jovian.decky-loader.user = "vera";
  jovian.steam.desktopSession = "plasma";

  jovian.devices.steamdeck.enable = lib.mkForce false;
  jovian.steamos.useSteamOSConfig = lib.mkForce false;
  jovian.hardware.amd.gpu.enableBacklightControl = true;

  services.openssh.openFirewall = true;

  services.handheld-daemon = {
    user = "vera";
    enable = true;
    ui.enable = true;
    adjustor.enable = true;
    adjustor.loadAcpiCallModule = true;
  };

  # Dolphin Bluetooth passthrough
  services.udev.extraRules = ''
    SUBSYSTEM=="usb", ATTRS{idVendor}=="8087", ATTRS{idProduct}=="0032", TAG+="uaccess"
  '';

  gradient.substituters = {
    asiyah = "ssh-ng://nix-ssh@asiyah.gradient?priority=40";
    bernkastel = "ssh-ng://nix-ssh@bernkastel.gradient?priority=40";
  };

}