{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.facter.reportPath = ./facter.json;

  boot.kernelPackages = pkgs.linuxPackages_zen;
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "amdgpu"
    "xhci_hcd"
    "tpm_crb"
  ];
  boot.initrd.kernelModules = [
    "kvm-amd"
    "amdgpu"
    "tpm_crb"
    "gpd-fan"
  ];
  boot.kernelModules = [
    "kvm-amd"
    "i2c-dev"
    "tpm_crb"
    "gpd-fan"
    "bmi270_i2c"
  ];
  boot.kernelParams = [
    "amd_iommu=on"
    "iommu=pt"
    "pcie_aspm=force"
    "rtc_cmos.use_acpi_alarm=1"

    "acpi_os_name=\"Microsoft Windows NT\""
    "acpi_osi=\"Windows 2015\""
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ ];
  boot.extraModprobeConfig = "";

  # Let EC control decide fan speed, see https://docs.kernel.org/6.18/hwmon/gpd-fan.html
  boot.kernel.sysfs.devices.platform.gpd_fan.hwmon."hwmon[0-9]*".pwm1_enable = 2;

  # Breaks suspend due to ppfeaturemask
  programs.corectrl = {
    enable = lib.mkForce false;
  };
  hardware.amdgpu.overdrive.enable = lib.mkForce false;

  # Touchpad and gamepad "mouse mode"
  services.udev.extraRules = ''
    SUBSYSTEM=="usb", ATTRS{idVendor}=="2f24", ATTRS{idProduct}=="0135", MODE="0666", GROUP="plugdev"

    # The HTIX5288 touchpad sometimes wakes up the mini laptop :(
    ACTION=="add|change", SUBSYSTEM=="i2c", KERNEL=="i2c-HTIX5288:00", ATTR{power/wakeup}="disabled"
  '';

  # Gyro control
  hardware.sensor.iio.enable = true;

  # Touchpad size calibration, generated by the following command:
  # libinput measure touchpad-size 48x39
  services.udev.extraHwdb = ''
    evdev:name:HTIX5288:00 0911:5288 Touchpad:dmi:*svnGPD:*pnG1617-01**
      EVDEV_ABS_00=12:2624:54
      EVDEV_ABS_01=74:1332:32
      EVDEV_ABS_35=12:2624:54
      EVDEV_ABS_36=74:1332:32
  '';

  # As per https://github.com/aarron-lee/gpd-win-tricks/tree/main/win4-suspend-mods
  # Use new bmi270 modules
  systemd.services.gpd-sleep-fix = {
    wantedBy = [ "sleep.target" ];
    before = [ "sleep.target" ];
    serviceConfig.User = "root";
    serviceConfig.Type = "oneshot";
    serviceConfig.RemainAfterExit = "yes";
    unitConfig.StopWhenUnneeded = "yes";
    path = [ pkgs.kmod ];
    script = ''
      echo "Unloading bmi270 modules..."
      modprobe -r bmi270_i2c
      modprobe -r bmi270_core
      echo "Done unloading modules!"
    '';
    postStop = ''
      echo "Loading bmi270 modules..."
      modprobe bmi270_i2c
      modprobe bmi270_core
      echo "Done loading modules!"
    '';
  };

  systemd.services.touchpad-fix = {
    description = "Retry i2c_hid_acpi probe for the Hantick HTIX5288 touchpad";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" ];
    serviceConfig = {
      type = "oneshot";
      RemainAfterExit = true;
    };
    path = [ pkgs.kmod ];
    script = ''
      expected_size=482
      tries=10

      bound() {
        desc=$(ls /sys/bus/hid/devices/*0911:5288*/report_descriptor 2>/dev/null | head -1)
        [ -n "$desc" ] && [ "$(wc -c < "$desc" 2>/dev/null)" -eq "$expected_size" ]
      }

      if bound; then
        echo "HTIX5288 touchpad bound cleanly at boot"
        exit 0
      fi

      attempt=1
      while [ "$attempt" -le "$tries" ]; do
        echo "HTIX5288 not bound (or bad descriptor), reload attempt $attempt/$tries"
        rmmod i2c_hid_acpi 2>/dev/null || true
        modprobe i2c_hid_acpi || true
        sleep 1
        if bound; then
          echo "HTIX5288 touchpad bound after $attempt reload(s)"
          exit 0
        fi
        attempt=$((attempt + 1))
      done

      echo "WARNING: HTIX5288 touchpad failed to bind after $tries attempts"
      exit 0
    '';
  };

  systemd.services.touchpad-resume-fix = {
    wantedBy = [ "sleep.target" ];
    before = [ "sleep.target" ];
    serviceConfig = {
      User = "root";
      Type = "oneshot";
      RemainAfterExit = true;
    };
    unitConfig.StopWhenUnneeded = true;
    path = [ pkgs.kmod ];
    script = "true";
    postStop = ''
      for attempt in 1 2 3 4 5; do
        rmmod i2c_hid_acpi 2>/dev/null || true
        modprobe i2c_hid_acpi || true
        sleep 1
        if ls /sys/bus/hid/devices/*0911:5288*/report_descriptor >/dev/null 2>&1; then
          echo "HTIX5288 re-probed after resume (attempt $attempt)"
          exit 0
        fi
      done
      echo "WARNING: HTIX5288 did not come back after resume"
      exit 0
    '';
  };

  nixpkgs.hostPlatform = "x86_64-linux";

}
