keys:
  - &user_vera age1w7xthmy2u80yp9jx98dnmcek0xcdcfmjx5at823m3536rkp5q3xqkqfw2j
  - &user_neith age10h2dan2d3jgy8tjq4djhu5lg4krx2m735nxcvg2schkpkvht0ynsmpdqne
  - &host_bernkastel age1hl9999dlv29qejtac0sdw7nnm9d06uh4nzmgc029ndg40vllavyq5u0pqu
  - &host_neithdeck age1uj0nmmvdeajg0hqlahe839c5r4n6nz0r6ampcwa46yhetx32kgrqqky22x
  - &host_erika age1ttl5pp50xffh73y3ekutsret24gd3rn7w2yvvcrhu2ywkz867fes8ea2s7
  - &host_asiyah age1lkh89lus8pzd83m2gkvsmyr9uql6n6c0xgwtq69eh0wxeaynxa3qfyzps4
  - &host_briah age10z4hmqp35sut8v03edvrqwgmuqcwa8sd0fckp3yvcz3x9j3xr4zs4y40ef
  - &host_featherine age1ejpz2fma32t2ek20t3v2x6cyjrzm50lhd9gwqsqhvhnr9nkc0gpscgndk2
  - &host_yetzirah age1ca2ptgj50tdc9lf20mlsq64efqkczd7zlvt49fdnk0z8u7qy7v8sha9tsy
  - &host_angela age1nzmuy9l4r02mmsc9g82u9dk63dn8x9508xs4m2jjpgujvnuer56q3pqh2v
  - &host_mute age1xnd9swcqfs6vaaxapuynk9ynd0t98536pf2e4qkghppeft43gyysfh5m7g
creation_rules:

  - path_regex: 'core/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *user_neith
      - *host_bernkastel
      - *host_neithdeck
      - *host_erika
      - *host_asiyah
      - *host_briah
      - *host_featherine
      - *host_yetzirah
      - *host_angela
      - *host_mute

  - path_regex: 'users/vera/secrets/*'
    key_groups:
    - age:
      - *user_vera
      
  - path_regex: 'users/neith/secrets/*'
    key_groups:
    - age:
      - *user_neith
      - *user_vera

  - path_regex: 'hosts/bernkastel/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_bernkastel

  - path_regex: 'hosts/erika/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_erika

  - path_regex: 'hosts/neith-deck/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *user_neith
      - *host_neithdeck

  - path_regex: 'hosts/asiyah/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_asiyah

  - path_regex: 'hosts/briah/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_briah

  - path_regex: 'hosts/yetzirah/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_yetzirah

  - path_regex: 'hosts/featherine/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_featherine

  - path_regex: 'hosts/angela/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_angela

  - path_regex: 'hosts/mute/secrets/*'
    key_groups:
    - age:
      - *user_vera
      - *host_mute