name: "Setup GradientNet VPN"
description: "Install and set up Wireguard with the GradientNet VPN for Forgejo Deployments on an Alpine runner."
inputs:
  wireguard-private-key:
    description: "The private Wireguard key to use for this host."
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: Evaluate Asiyah Wireguard public key
      uses: actions/eval-nix@v1
      id: asiyahpubkey
      with:
        file: ./misc/wireguard-pub-keys.nix
        expresion: "asiyah"
        extraArgs: "--raw"
    - name: Evaluate Asiyah Wireguard address
      uses: actions/eval-nix@v1
      id: asiyahaddress
      with:
        file: ./misc/wireguard-addresses.nix
        expresion: "gradientnet.asiyah"
        extraArgs: "--raw"
    - name: Evaluate Forgejo Deployment Wireguard address
      uses: actions/eval-nix@v1
      id: forgejodeploymentaddress
      with:
        file: ./misc/wireguard-addresses.nix
        expresion: "gradientnet.forgejo-deployment"
        extraArgs: "--raw"
    - name: Evaluate GradientNet Wireguard address
      id: gradientnetaddress
      uses: actions/eval-nix@v1
      with:
        file: ./misc/wireguard-addresses.nix
        expresion: "gradientnet.gradientnet"
        extraArgs: "--raw"
    - name: Evaluate GradientNet Port
      id: gradientnetport
      uses: actions/eval-nix@v1
      with:
        file: ./hosts/asiyah/misc/service-ports.nix
        expresion: "gradientnet"
        extraArgs: "--raw"
    - name: Setup GradientNet
      uses: actions/setup-wireguard@v1
      with:
        wireguard-interface-name: gradientnet
        wireguard-private-key: ${{ inputs.wireguard-private-key }}
        wireguard-address: ${{ steps.forgejodeploymentaddress.result }}
        wireguard-peer-address: ${{ steps.asiyahaddress.result }}
        wireguard-peer-public-key: ${{ steps.asiyahpubkey.result }}
        wireguard-peer-endpoint: vpn.gradient.moe:${{ steps.gradientnetport.result }}
        wireguard-peer-allowed-ips: ${{ steps.gradientnetaddress.result }}/24
