name: "Setup GradientNet VPN"
description: "Install and set up Wireguard with the GradientNet VPN for Forgejo Deployments on an Alpine runner."
inputs:
  wireguard-private-key:
    description: "The private Wireguard key to use for this host."
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: Evaluate Asiyah Wireguard public key
      uses: actions/eval-nix@v1
      id: asiyahpubkey
      with:
        file: ./misc/wireguard-pub-keys.nix
        expr: asiyah
        extraArgs: --raw
    - name: Evaluate GradientNet Wireguard address
      id: gradientnetaddress
      uses: actions/eval-nix@v1
      with:
        file: ./misc/wireguard-addresses.nix
        expr: gradientnet.gradientnet
        extraArgs: --raw
    - name: Evaluate Forgejo Deployment Wireguard address
      id: forgejoaddress
      uses: actions/eval-nix@v1
      with:
        file: ./misc/wireguard-addresses.nix
        expr: gradientnet.forgejo-deployment
        extraArgs: --raw
    - name: Evaluate GradientNet Port
      id: gradientnetport
      uses: actions/eval-nix@v1
      with:
        file: ./hosts/asiyah/misc/service-ports.nix
        expr: gradientnet
    - name: Disable SSH Strict Host Key Checking for GradientNet
      run: |
        HOST=$(echo ${{ steps.gradientnetaddress.outputs.result }} | rev | cut -c 2- | rev | cat - <(echo "*") | tr -d '\n')
        echo "Disabling SSH Strict Host Key checking for $HOST"
        echo "Host $HOST" >> ~/.ssh/config
        echo "    StrictHostKeyChecking=no" >> ~/.ssh/config
    - name: Setup GradientNet
      uses: actions/setup-wireguard@v1
      with:
        wireguard-interface: fgjdplygrdnt0
        wireguard-config: |
          [Interface]
          Address = ${{ steps.forgejoaddress.outputs.result }}/32
          PrivateKey = ${{ inputs.wireguard-private-key }}

          [Peer]
          PublicKey = ${{ steps.asiyahpubkey.outputs.result }}
          AllowedIPs = ${{ steps.gradientnetaddress.outputs.result }}/24
          Endpoint = vpn.gradient.moe:${{ steps.gradientnetport.outputs.result }}
          PersistentKeepalive = 25