esphome:
  name: bk7231n-ir-blaster
  friendly_name: BK7231N IR Blaster
  name_add_mac_suffix: true

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: latest

api:
logger:
  baud_rate: 9600
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.102
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "BK7231N-IR-Blaster"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80
  include_internal: true
  local: true

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

remote_transmitter:
  pin: GPIO7
  carrier_duty_percent: 50%

remote_receiver:
  pin: GPIO8
  dump: all

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor

climate:
  - platform: midea_ir
    name: "Vera Bedroom AC"
