esphome:
  name: smart-doorbell-esp-wroom-32
  friendly_name: smart-doorbell-esp-wroom-32

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: recommended

logger:

api:

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "Smart-Doorbell-Esp-Wroom-32"
    password: !secret ap_password

captive_portal:

sensor:
  - platform: adc
    pin: GPIO32
    name: "Doorbell Voltage"
    update_interval: 0.5s