name: Run Colmena Deployment
on:
  workflow_dispatch:
    inputs:
      operation:
        description: Which NixOS build operation to use.
        default: "switch"
        type: choice
        options:
          - switch
          - boot
          - push
      hosts:
        description: Which hosts to target.
        required: true
        type: string
      build-on-target:
        description: Build on target
        default: false
        required: false
        type: boolean
      update-inputs:
        description: Whether to update flake inputs before deployment.
        default: false
        type: boolean
        required: true
      inputs-to-update:
        description: 'Flake inputs to update, leave empty to update all inputs. Only used if "Update Inputs" is set.'
        default: ""
        type: string
        required: false
env:
  # Listen, listen, listen...
  # Life's too short for this crap, eh?
  NIXPKGS_ALLOW_INSECURE: 1
  NIXPKGS_ALLOW_BROKEN: 1
jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup SSH
        id: setupssh
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup GradientNet
        uses: ./.forgejo/setup-gradientnet
        with:
          wireguard-private-key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      - name: Setup Attic Cache
        uses: ./.forgejo/setup-attic-cache
        with:
          attic-token: ${{ secrets.ATTIC_TOKEN }}
      - name: Install Colmena
        run: nix profile install nixpkgs#lixPackageSets.latest.colmena --inputs-from $FORGEJO_WORKSPACE
      - name: Update flake inputs
        if: ${{ inputs.update-inputs }}
        run: nix flake update ${{ inputs.inputs-to-update }}
      - name: Fetch flake inputs
        run: nix flake archive --no-update-lock-file
      - name: Run Colmena Apply with build on target
        id: colmenabuild
        if: ${{ inputs.build-on-target }}
        continue-on-error: true
        run: colmena apply ${{ inputs.operation }} --on "${{ inputs.hosts }}" --show-trace --impure --evaluator=streaming --build-on-target 
      - name: Run Colmena Apply with no build on target
        id: colmenabuildnotarget
        if: ${{ !inputs.build-on-target }}
        continue-on-error: true
        run: colmena apply ${{ inputs.operation }} --on "${{ inputs.hosts }}" --show-trace --impure --evaluator=streaming --no-build-on-target
      - name: Commit flake.lock
        if: ${{ inputs.update-inputs && steps.colmenabuild.outcome != 'failure' && steps.colmenabuildnotarget.outcome == 'failure' }}
        run: |
          echo "Configure Git"
          git config --global user.name "Forgejo Deployment"
          git config --global user.email "vera@noreply.git.gradient.moe"
          echo "Commiting and pushing flake.lock"
          git add flake.lock
          git commit -m "Update gradient.moe input"
          git push
          echo "Done!"
      - name: Cache all store paths to Attic
        uses: ./.forgejo/cache-to-attic
      - name: On failure
        if: ${{ steps.colmenabuild.outcome == 'failure' || steps.colmenabuildnotarget.outcome == 'failure' }}
        run: exit 1