name: Run Colmena Deployment
on:
  workflow_dispatch:
    inputs:
      operation:
        description: Which NixOS build operation to use.
        default: "switch"
        type: choice
        options:
          - switch
          - boot
          - push
      hosts:
        description: Which hosts to target.
        required: true
        type: string
      build-on-target:
        description: Build on target
        default: false
        required: false
        type: boolean

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install tar
        run: apk add tar
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Setup SSH
        id: setupssh
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup GradientNet
        uses: ./.forgejo/setup-gradientnet
        with:
          wireguard-private-key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      - name: Setup Attic Cache
        uses: ./.forgejo/setup-attic-cache
        with:
          attic-token: ${{ secrets.ATTIC_TOKEN }}
      - name: Fetch flake inputs
        run: nix flake archive
      - name: Run Colmena Apply with build on target
        if: ${{ inputs.build-on-target }}
        run: nix run .#colmena -- apply ${{ inputs.operation }} --on "${{ inputs.hosts }}" --show-trace --evaluator=streaming --build-on-target 
      - name: Run Colmena Apply with no build on target
        if: ${{ !inputs.build-on-target }}
        run: nix run .#colmena -- apply ${{ inputs.operation }} --on "${{ inputs.hosts }}" --show-trace --evaluator=streaming --no-build-on-target