name: Build all systems
on:
  # Nightly build at 4 AM
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
env:
  # Listen, listen, listen...
  # Life's too short for this crap, eh?
  NIXPKGS_ALLOW_INSECURE: 1
  NIXPKGS_ALLOW_BROKEN: 1
jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup SSH
        id: setupssh
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Attic Cache
        uses: ./.forgejo/setup-attic-cache
        with:
          attic-token: ${{ secrets.ATTIC_TOKEN }}
      - name: Install Colmena
        run: nix profile install nixpkgs#lixPackageSets.latest.colmena --inputs-from $FORGEJO_WORKSPACE
      - name: Fetch flake inputs
        run: nix flake archive --no-update-lock-file
      - name: Run Colmena Build
        id: colmenabuild
        run: colmena apply build --on @nightly --show-trace --evaluator=streaming --impure --no-build-on-target
        continue-on-error: true
      - name: Cache all store paths to Attic
        uses: ./.forgejo/cache-to-attic
      - name: On failure
        if: ${{ steps.colmenabuild.outcome == 'failure' }}
        run: exit 1