name: Build all systems
on:
  # Nightly build at 4 AM
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Setup SSH
        id: setupssh
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Attic Cache
        uses: ./.forgejo/setup-attic-cache
        with:
          attic-token: ${{ secrets.ATTIC_TOKEN }}
      - name: Fetch flake inputs
        run: nix flake archive
      - name: Run Colmena Build
        run: nix run .#colmena -- apply build --on "*" --show-trace --evaluator=streaming --no-build-on-target