on: [push, workflow_dispatch]
name: Check Flake
jobs:
  nix-flake-check:
    runs-on: alpine-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Setup SSH
        id: setupssh
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup GradientNet
        uses: ./.forgejo/setup-gradientnet
        with:
          wireguard-private-key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      - name: Run nix flake check
        run: nix flake check