name: "Update gradient.moe input and deploy to Asiyah"
on:
  workflow_dispatch:
env:
  # Listen, listen, listen...
  # Life's too short for this crap, eh?
  NIXPKGS_ALLOW_INSECURE: 1
  NIXPKGS_ALLOW_BROKEN: 1
jobs:
  build:
    runs-on: alpine-latest
    steps:
      - name: Install Lix
        uses: actions/install-lix@v1
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup SSH
        id: setupssh
        uses: actions/setup-ssh@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup GradientNet
        uses: ./.forgejo/setup-gradientnet
        with:
          wireguard-private-key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
      - name: Setup Attic Cache
        uses: ./.forgejo/setup-attic-cache
        with:
          attic-token: ${{ secrets.ATTIC_TOKEN }}
      - name: Install Colmena
        run: nix profile install nixpkgs#lixPackageSets.latest.colmena --inputs-from $FORGEJO_WORKSPACE
      - name: Update gradient.moe flake input
        run: nix flake update gradient-moe
      - name: Fetch flake inputs
        run: nix flake archive --no-update-lock-file
      - name: Deploy to Asiyah
        id: colmena
        if: ${{ !inputs.build-on-target }}
        continue-on-error: true
        run: colmena apply switch --on "asiyah" --show-trace --impure --evaluator=streaming --no-build-on-target
      - name: Commit flake.lock
        if: ${{ steps.colmena.outcome != 'failure' }}
        run: |
          echo "Commiting and pushing flake.lock"
          git add flake.lock
          git commit -m "Update gradient.moe input"
          git push
          echo "Done!"
      - name: Cache all store paths to Attic
        uses: ./.forgejo/cache-to-attic
      - name: On failure
        if: ${{ steps.colmena.outcome == 'failure' }}
        run: exit 1