ota_password: ENC[AES256_GCM,data:AhjKyiXbaIqG,iv:yut8wQX3xtO5DY44JxQkDww8OUx2jCL9Let78CcqQ5A=,tag:9+IHUiOejaK04F/8rPbq7w==,type:str]
wifi_ssid: ENC[AES256_GCM,data:ySfVww==,iv:dJ2AExHpdG6mhm25bSym7DcJlNviNb5oi8UakYQxn6c=,tag:JkvL22BH5vOffBLU/anTsA==,type:str]
wifi_password: ENC[AES256_GCM,data:inB+z+f4uRDcGKgjEUA=,iv:E4BJd0zdSaU2x92AHhrKce6z6SkpnArx+/q8gj3evxM=,tag:0s+USnVMrsLiLfSE53PiGQ==,type:str]
ap_password: ENC[AES256_GCM,data:YoqTfH0juEAQTEhqZQOeqiSWUe4Q1g==,iv:uvzn+oSGl4Bj/tGttnRkKI65qP+uqKSjznmhfGlMMzM=,tag:GDc1LDtKBX8qKIr0Mw4p/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w7xthmy2u80yp9jx98dnmcek0xcdcfmjx5at823m3536rkp5q3xqkqfw2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbGFzSCtVYVJaazJtbEhh
            UFd6Skx2WTFDd3hQTDFDWjU4RWV3OUxWekJNCjVpU2lkWE5pTjd0dWJlcEVZREdu
            bHhPNXNMUkNnN3FqbHQ4bmZBWVRJRTAKLS0tIEx0L1EyR004anJzZWxONC9JZkR0
            b0tHWHpPQnd4UWVoLzhPbVNGUmNlZlkKhH3UauIjw8Q95IIQCY1QoFNjulpQ8b79
            FQslta5WXPg/PAHYcE2R2LAA7NcV93QwsOAMFfIYY6gB73acNBVfUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mlznec0ruk9xgkzygpmetsfvutxk4qml636rqcvzpzudyp4wlcfqzgh2e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc3NKT215SmxkL20xMUw4
            K3VzWnFkT2EwaFJ3WTV2amo4UC9qZUFTMGlJClNMaUYrcVB1OUgzeVlsMGVnVVFs
            UlhLZitMbTIvSWw2NW9yNzZWdkxtL3MKLS0tIC95WHMwcTNhSExlalpuOVJsZnlM
            YW84aWNkRzNacS9pRTdRcDBUVVJmTnMKjMquVRza/847VfY16xie989s29tMNrLG
            6HSlglMjqOzKxnC0bfD9Qq++Cvcvp2HP3YJb+cXV+ed6XpZDxZLx7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T12:57:03Z"
    mac: ENC[AES256_GCM,data:Hysv+wpRGriXUdPDsFG0nUH++WCfdpMby/DWWULjuVVysNZnKD0Xlby4QqHfOoupHDxgj7lAUdfhetNCSghbjkRuwdPSd1wDAA4cXiUQDhLU3GnMqCtdVlyhXL2i2nHnqM8pb2kqAhq0GLAnYgqfd6bkxRdrGt2TaYj7JjTJKa0=,iv:oi4cfJ5b9ZexycPbs3s9bCuO8xm2SRf4umivkXHn4Ek=,tag:Mxno5I2NJt3gbdR+UMtlOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
