name: "Cache all store paths to Gradient Attic"
description: "Install and set up the Attic client with a cache."
outputs: {}
runs:
  using: composite
  steps:
    - name: "Cache all store paths to Gradient Attic"
      run: |
        echo "Caching all store paths to Gradient Attic..."
        nix build nixpkgs#attic-client
        find /nix/store -mindepth 1 -maxdepth 1 -type d -not -name '.*' | ./result/bin/attic push gradient --stdin
        echo "Cached all paths successfully!"