name: "Cache all store paths to Gradient Attic"
description: "Caches all store paths under /nix/store to an Attic cache. The Attic client must be available on PATH."
outputs: {}
runs:
  using: composite
  steps:
    - name: "Cache all store paths to Gradient Attic"
      run: |
        echo "Caching all store paths to Gradient Attic..."
        find /nix/store -mindepth 1 -maxdepth 1 -type d -not -name '.*' -exec attic push gradient {} \;
        echo "Cached all paths successfully!"