esphome:
  name: bk7231n-ir-blaster
  friendly_name: BK7231N IR Blaster
  name_add_mac_suffix: false

bk72xx:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: recommended

api:
logger:
  baud_rate: 9600
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.102
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "BK7231N-IR-Blaster"
    password: !secret ap_password

captive_portal:

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

remote_transmitter:
  pin: GPIO7
  carrier_duty_percent: 50%
  id: irtx

remote_receiver:
  pin:
    number: GPIO8 
    inverted: true
  dump: all
  tolerance: 50%
  id: irrx

uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
  - platform: uptime
    type: seconds
    name: Uptime Sensor

binary_sensor:
  - platform: status
    name: IR Blaster Status