substitutions:
  name: ESPBell-LITE

esphome:
  name: espbell-lite
  friendly_name: ESPBell LITE
  name_add_mac_suffix: false
  project:
    name: pricelesstoolkit.espbell-lite
    version: "1.0"

esp8266:
  board: esp12e

dashboard_import:
  package_import_url: github://PricelessToolkit/ESPBell-LITE/Code/ESPHome/espbell-lite.yaml@main
  import_full_config: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

wifi:
  fast_connect: on
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      bssid: "80:AF:CA:56:F8:96"
      manual_ip: 
        static_ip: "192.168.1.107"
        gateway: "192.168.1.1"
        subnet: "255.255.255.0"
  ap:
    ssid: "espbell-lite"
    password: !secret ap_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
  - platform: uptime
    type: seconds
    name: Uptime Sensor

binary_sensor:
  
  - platform: status
    name: ESPBell Lite Controller Status

# Doorbell Sensor
  - platform: gpio
    pin:
      number: 4
      #inverted: true
    name: "DoorBell"
    icon: "mdi:bell"
    filters:
      delayed_on: 100ms

  - platform: status
    name: "${name} Status"

# switch:

# Door Lock Opener "Momentary Switch" Keeps SSR ON for 1.5s.
#  - platform: gpio
#    pin: 5
#    id: Lock
#    name: "Lock"
#    icon: "mdi:lock"
#    restore_mode: ALWAYS_OFF
#    on_turn_on:
#    - delay: 1500ms
#    - switch.turn_off: Lock

button:
  - platform: restart
    name: ${name} restart