esphome:
  name: air-freshener-vera-bedroom
  friendly_name: Air Freshener Vera Bedroom
  name_add_mac_suffix: false

external_components:
  - source: "github://gabest11/esphome@0d73a86e1b4ac0920110c484993e8c998d2880b9"
    components: [ cc1101 ]

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: recommended

logger:

mdns:
  disabled: false

ota:
  - platform: esphome
    id: ota_esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "Air Freshener ESP32"
    password: !secret ap_password

captive_portal:

output:
  - platform: esp32_dac
    pin: GPIO25
    id: dac_output
  - platform: esp32_dac
    pin: GPIO26
    id: dac_output_inv

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      icon: mdi:wifi
    ssid:
      name: "Connected SSID"
      icon: mdi:wifi-strength-2

#esp32_ble_tracker:
#  scan_parameters:
#    active: True # Whether to send scan-request packets to devices to gather more info (like devicename)
#    interval: 320ms # suggested 211ms # default 320ms
#    window:   30ms # suggested 120ms # default 30ms

#bluetooth_proxy:
#  id: ble_proxy
#  active: true  # allows outbound connections from HA to devices.

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 120s
  - platform: uptime
    type: seconds
    name: Uptime Sensor
  - platform: internal_temperature
    name: "ESP32 Internal Temperature"

spi:
  clk_pin: GPIO17
  miso_pin: GPIO27
  mosi_pin: GPIO16

cc1101:
  id: transceiver
  cs_pin: GPIO19
  output_power: 0
  tuner:
    frequency: 434110
    # if_frequency: 153
    # bandwidth: 325
    # channel: 0
    # channel_spacing: 200
    # fsk_deviation: 47.607
    # msk_deviation: 0
    # symbol_rate: 5000
    # sync_mode: None
    # carrier_sense_above_threshold: true
    # modulation: ASK/OOK
  # agc:    
    # magn_target:
    # max_lna_gain:
    # max_dva_gain:
    # carrier_sense_abs_thr:
    # carrier_sense_rel_thr:
    # lna_priority:
    # filter_length_fsk_msk:
    # filter_length_ask_ook:
    # freeze:
    # wait_time:
    # hyst_level:
  sensor:
    chip_id:
      name: Chip Id
    rssi:
      name: RSSI
    lqi:
      name: LQI
    temperature:
      name: Temperature

number:
  - platform: cc1101
    output_power:
      name: output_power
      id: cc1101_output_power
    tuner:
      frequency:
        name: Tuner frequency
        id: cc1101_freq
      if_frequency:
        name: Tuner if_frequency
      bandwidth:
        name: Tuner bandwidth
      channel:
        name: Tuner channel
      channel_spacing:
        name: Tuner channel_spacing
      fsk_deviation:
        name: Tuner fsk_deviation
      msk_deviation:
        name: Tuner msk_deviation
      symbol_rate:
        name: Tuner symbol_rate
    agc:
      carrier_sense_abs_thr:
        name: AGC carrier_sense_abs_thr
  - platform: template
    id: ceiling_fan_signal_repeat
    name: Ceiling Fan Signal Repeat Times
    internal: true
    optimistic: True
    min_value: 1
    max_value: 40
    step: 1
    initial_value: 4

select:
  - platform: cc1101
    tuner:
      sync_mode:
        name: Tuner Sync Mode
      modulation:
        name: Tuner Modulation
    agc:
      magn_target:
        name: AGC magn_target
      max_lna_gain:
        name: AGC max_lna_gain
      max_dvga_gain:
        name: AGC max_dva_gain
      carrier_sense_rel_thr:
        name: AGC carrier_sense_rel_thr
      filter_length_fsk_msk:
        name: AGC filter_length_fsk_msk
      filter_length_ask_ook:
        name: AGC filter_length_ask_ook
      freeze:
        name: AGC freeze
      wait_time:
        name: AGC wait_time
      hyst_level:
        name: AGC hyst_level

switch:
  - platform: cc1101
    tuner:
      carrier_sense_above_threshold:
        name: Tuner carrier_sense_above_threshold
    agc:
      lna_priority:
        name: AGC lna_priority

remote_transmitter:
  pin: GPIO18  # GDO0
  carrier_duty_percent: 100%
  on_transmit:
    then:
      #- esp32_ble_tracker.stop_scan:
      #- lambda: |- 
      #     id(ble_proxy)->set_active(false);
      - cc1101.begin_tx: transceiver
  on_complete:
    then:
      - cc1101.end_tx: transceiver
      #- lambda: |- 
      #     id(ble_proxy)->set_active(true);
      #- esp32_ble_tracker.start_scan:
      #      continuous: true
remote_receiver:
  pin: GPIO14  # GDO2
  # dump:
    # - rc_switch
    # - raw
  tolerance: 50%
  filter: 250us
  idle: 4ms

api:
  services:
    - service: 'remote_transmit_raw'
      variables:
        code: int[]
        repeat: int
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return code;'
            repeat: 
              times: !lambda 'return repeat;'
    - service: 'remote_transmit_cc1101_ceiling_fan_code'
      variables:
        code: string
        repeat: int
      then:
        - lambda: id(cc1101_transmit_ceiling_fan_code)->execute(code, repeat);

script:
  - id: cc1101_transmit_ceiling_fan_code
    parameters:
      code: string
      repeat: int
    then:
      - number.set:
          id: cc1101_freq
          value: 434110
      - number.set:
          id: cc1101_output_power
          value: 7
      - remote_transmitter.transmit_raw:
          code: !lambda |-
            std::vector<long int> vec;
            for (int i = 0; i < code.length(); i++) {
              if (code[i] == '0') {
                vec.push_back(740);
                vec.push_back(-256);
              } else if (code[i] == '1') {
                vec.push_back(256);
                vec.push_back(-740);
              }
            }
            vec.push_back(256);
            vec.push_back(-8864);
            return vec;
          repeat: 
            times: !lambda 'return repeat;'
            wait_time: 0s

button:
  - platform: restart
    name: "Restart"
  - platform: template
    name: Spray
    id: spray
    icon: "mdi:spray"
    on_press:
      - logger.log: "Spraying..."
      - output.turn_on: dac_output_inv
      - output.turn_on: dac_output
      - output.set_level:
          id: dac_output_inv
          level: 100%
      - output.set_level:
          id: dac_output
          level: 0%
      - delay: 0.5s
      - output.set_level:
          id: dac_output_inv
          level: 0%
      - output.set_level:
          id: dac_output
          level: 25%
      - delay: 0.25s
      - output.turn_off: dac_output
      - output.turn_off: dac_output_inv
      - logger.log: "Sprayed!"
  - platform: template
    name: Ceiling Fan Light Toggle
    icon: "mdi:ceiling-fan-light"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001110011111101", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Toggle
    icon: "mdi:ceiling-fan"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001110110101001", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Speed 1
    icon: "mdi:fan-chevron-down"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001011110000001", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Speed 2
    icon: "mdi:fan-chevron-down"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001011011010101", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Speed 3
    icon: "mdi:fan-chevron-down"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001000110110100", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Speed 4
    icon: "mdi:fan-chevron-up"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001101010101110", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Speed 5
    icon: "mdi:fan-chevron-up"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001100000010111", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Speed 6
    icon: "mdi:fan-chevron-up"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001100110001111", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Direction Toggle
    icon: "mdi:arrow-left-right"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001111011111111", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Dim Light
    icon: "mdi:lightbulb-on-20"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001011100101011", id(ceiling_fan_signal_repeat).state); 
  - platform: template
    name: Ceiling Fan Brighten Light
    icon: "mdi:lightbulb-on-80"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001101111001001", id(ceiling_fan_signal_repeat).state); 
  - platform: template
    name: Ceiling Fan Warm Light Color
    icon: "mdi:heat-wave"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001100100110100", id(ceiling_fan_signal_repeat).state); 
  - platform: template
    name: Ceiling Fan Neutral Light Color
    icon: "mdi:emoticon-neutral-outline"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001100011111001", id(ceiling_fan_signal_repeat).state); 
  - platform: template
    name: Ceiling Fan Cold Light Color
    icon: "mdi:snowflake"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001011001011101", id(ceiling_fan_signal_repeat).state);
  - platform: template
    name: Ceiling Fan Natural Wind
    icon: "mdi:weather-windy"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001010100111000", id(ceiling_fan_signal_repeat).state); 
  - platform: template
    name: Ceiling Fan 30 Minutes Timer
    icon: "mdi:fan-clock"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001101100010100", id(ceiling_fan_signal_repeat).state); 
  - platform: template
    name: Ceiling Fan 2 Hours Timer
    icon: "mdi:fan-clock"
    on_press:
      - lambda: id(cc1101_transmit_ceiling_fan_code)->execute("11111101001111001001001100001101", id(ceiling_fan_signal_repeat).state); 

binary_sensor:
  - platform: status
    name: Air Freshener Status