name: "Setup Gradient Attic Cache"
description: "Install and set up the Attic client with a cache."
inputs:
  attic-token:
    description: "The private token to log in with."
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: "Install Attic Client"
      run: |
        echo "Installing Attic client..."
        nix profile install nixpkgs#attic-client --inputs-from $FORGEJO_WORKSPACE
    - name: "Log into Attic"
      run: |
        echo "Logging into Attic server..."
        attic login gradient https://cache.gradient.moe ${{ inputs.attic-token }}
        echo "Logged in!"
    - name: "Use Attic Gradient Cache"
      run: |
        echo "Enabling Gradient cache..."
        attic use gradient
        nohup attic watch-store gradient &
        echo "Now using the Gradient cache!"